---
redis:
  host: 127.1
  port: 6379
  metrics:
    - name: somecmd
      cmd:  llen
      args: clientbeholdindex
      tags:
        - sometag: testme
        - sometag2: tesmeagain
    - name: anothercmd
      cmd:  lpop
      args: clientbeholdindex
